// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestGame.Repository;

namespace TestGame.Repository.Migrations
{
    [DbContext(typeof(TestGameContext))]
    partial class TestGameContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestGame.Repository.DAOs.ClientDAO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_Clients_Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("TestGame.Repository.DAOs.LobbyDAO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HostHealth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("10");

                    b.Property<int>("HostId")
                        .HasColumnType("int");

                    b.Property<int>("MovesCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SecondClientHealth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("10");

                    b.Property<int?>("SecondClientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("WinnerId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Lobbies_Id");

                    b.HasIndex("HostId");

                    b.HasIndex("SecondClientId");

                    b.HasIndex("WinnerId");

                    b.ToTable("Lobbies");
                });

            modelBuilder.Entity("TestGame.Repository.DAOs.LobbyDAO", b =>
                {
                    b.HasOne("TestGame.Repository.DAOs.ClientDAO", "Host")
                        .WithMany("LobbyHostIdNavigations")
                        .HasForeignKey("HostId")
                        .HasConstraintName("FK_Lobbies_HostId")
                        .IsRequired();

                    b.HasOne("TestGame.Repository.DAOs.ClientDAO", "SecondClient")
                        .WithMany("LobbySecondClientIdNavigations")
                        .HasForeignKey("SecondClientId")
                        .HasConstraintName("FK_Lobbies_SecondClientId");

                    b.HasOne("TestGame.Repository.DAOs.ClientDAO", "Winner")
                        .WithMany("LobbyWinnerIdNavigations")
                        .HasForeignKey("WinnerId")
                        .HasConstraintName("FK_Lobbies_WinnerId");

                    b.Navigation("Host");

                    b.Navigation("SecondClient");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("TestGame.Repository.DAOs.ClientDAO", b =>
                {
                    b.Navigation("LobbyHostIdNavigations");

                    b.Navigation("LobbySecondClientIdNavigations");

                    b.Navigation("LobbyWinnerIdNavigations");
                });
#pragma warning restore 612, 618
        }
    }
}
